Handle colon-delimited environmentpath in config_version.sh
puppetlabs/control-repo pull request #64
Opened 2018-03-29 21:19 UTC by mbaynton

`environment.conf` passes the Puppet configuration value `$environmentpath` as an argument to `config_version.sh`. This value [supports a colon-separated list](https://puppet.com/docs/puppet/5.4/config_file_main.html#paths) of paths, but when one is used the config_version scripts currently bomb out.

This fixes them to handle colon-delimited `environmentpath`.

2018-03-29 22:03 UTC, natemccurdy commented
@mbaynton Can you share an example of the script bombing out?

`$environmentpath`, when used in the context of this script should not be colon-separated. A node can only be in one environment so the environment path can only be one directory.

2018-03-29 22:06 UTC, natemccurdy requested changes

2018-03-29 22:06 UTC, natemccurdy commented on scripts/config_version.sh
> +RONMENTPATH=$1
Looks like a typo here.

2018-03-29 22:12 UTC, mbaynton commented on scripts/config_version.sh
> +RONMENTPATH=$1
Fixed!

2019-11-14 10:07 UTC, abuxton commented
Apologies this as taken so long to get to @mbaynton can you rebase the pull request please and if it's still required i'll merge it in.

2019-11-16 22:28 UTC, mbaynton commented
Rebased and merged @abuxton 
Full disclosure I don't currently use Puppet anymore so my ability to test is limited, but did try just invoking the merged version on some different inputs.

2020-02-11 00:34 UTC, natemccurdy commented
I just ran into a similar situation where a `:` delimited environmentpath wasn't working and used this PR for inspiration to fix fork of config_version.sh

It works 👍

Though I do have a minor style nitpick about using upper case variables for things that aren't environment variables.

2021-02-24 17:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/control-repo?pullRequest=64) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/control-repo?pullRequest=64) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/control-repo?pullRequest=64) it.</sub>

2026-05-29 00:58 UTC, zaben903 commented
Closing as a legacy, long standing PR.

2026-05-29 00:58 UTC, closed without merging